# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'filter_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGridLayout, QLabel,
    QPushButton, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(314, 541)
        self.gridLayout = QGridLayout(Form)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.pushButton_2 = QPushButton(Form)
        self.pushButton_2.setObjectName(u"pushButton_2")
        icon = QIcon()
        icon.addFile(u"../icons/cleaning_services_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_2.setIcon(icon)

        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)

        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)

        self.comboBox_2 = QComboBox(Form)
        icon1 = QIcon()
        icon1.addFile(u"../icons/captive_portal_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_2.addItem(icon1, "")
        self.comboBox_2.addItem(icon1, "")
        icon2 = QIcon()
        icon2.addFile(u"../icons/desktop_windows_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_2.addItem(icon2, "")
        icon3 = QIcon()
        icon3.addFile(u"../icons/desktop_mac_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_2.addItem(icon3, "")
        self.comboBox_2.addItem(icon2, "")
        icon4 = QIcon()
        icon4.addFile(u"../icons/android_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_2.addItem(icon4, "")
        icon5 = QIcon()
        icon5.addFile(u"../icons/mobile_2_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_2.addItem(icon5, "")
        self.comboBox_2.setObjectName(u"comboBox_2")

        self.gridLayout.addWidget(self.comboBox_2, 2, 0, 1, 2)

        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 2)

        self.comboBox_3 = QComboBox(Form)
        icon6 = QIcon()
        icon6.addFile(u"../icons/hov_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_3.addItem(icon6, "")
        icon7 = QIcon()
        icon7.addFile(u"../icons/percent_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_3.addItem(icon7, "")
        icon8 = QIcon()
        icon8.addFile(u"../icons/paid_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_3.addItem(icon8, "")
        self.comboBox_3.addItem(icon8, "")
        self.comboBox_3.addItem(icon8, "")
        self.comboBox_3.setObjectName(u"comboBox_3")

        self.gridLayout.addWidget(self.comboBox_3, 4, 0, 1, 2)

        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 2)

        self.comboBox_4 = QComboBox(Form)
        icon9 = QIcon()
        icon9.addFile(u"../icons/today_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_4.addItem(icon9, "")
        icon10 = QIcon()
        icon10.addFile(u"../icons/date_range_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_4.addItem(icon10, "")
        icon11 = QIcon()
        icon11.addFile(u"../icons/calendar_month_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_4.addItem(icon11, "")
        self.comboBox_4.setObjectName(u"comboBox_4")

        self.gridLayout.addWidget(self.comboBox_4, 6, 0, 1, 2)

        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")

        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 2)

        self.comboBox_5 = QComboBox(Form)
        icon12 = QIcon()
        icon12.addFile(u"../icons/falling_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon12, "")
        icon13 = QIcon()
        icon13.addFile(u"../icons/hiking_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon13, "")
        icon14 = QIcon()
        icon14.addFile(u"../icons/playing_cards_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon14, "")
        icon15 = QIcon()
        icon15.addFile(u"../icons/school_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon15, "")
        icon16 = QIcon()
        icon16.addFile(u"../icons/sports_martial_arts_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon16, "")
        icon17 = QIcon()
        icon17.addFile(u"../icons/format_clear_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon17, "")
        icon18 = QIcon()
        icon18.addFile(u"../icons/directions_run_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon18, "")
        icon19 = QIcon()
        icon19.addFile(u"../icons/extension_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon19, "")
        icon20 = QIcon()
        icon20.addFile(u"../icons/motorcycle_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon20, "")
        icon21 = QIcon()
        icon21.addFile(u"../icons/nightlife_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon21, "")
        icon22 = QIcon()
        icon22.addFile(u"../icons/castle_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon22, "")
        icon23 = QIcon()
        icon23.addFile(u"../icons/target_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon23, "")
        icon24 = QIcon()
        icon24.addFile(u"../icons/simulation_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon24, "")
        self.comboBox_5.addItem(icon18, "")
        icon25 = QIcon()
        icon25.addFile(u"../icons/strategy_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon25, "")
        icon26 = QIcon()
        icon26.addFile(u"../icons/cardiology_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon26, "")
        icon27 = QIcon()
        icon27.addFile(u"../icons/planner_banner_ad_pt_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon27, "")
        icon28 = QIcon()
        icon28.addFile(u"../icons/alt_route_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_5.addItem(icon28, "")
        self.comboBox_5.setObjectName(u"comboBox_5")

        self.gridLayout.addWidget(self.comboBox_5, 8, 0, 1, 2)

        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")

        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 2)

        self.comboBox_6 = QComboBox(Form)
        icon29 = QIcon()
        icon29.addFile(u"../icons/keyboard_alt_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon29, "")
        icon30 = QIcon()
        icon30.addFile(u"../icons/mouse_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon30, "")
        icon31 = QIcon()
        icon31.addFile(u"../icons/stadia_controller_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon31, "")
        self.comboBox_6.addItem(icon31, "")
        icon32 = QIcon()
        icon32.addFile(u"../icons/joystick_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon32, "")
        self.comboBox_6.addItem(icon5, "")
        icon33 = QIcon()
        icon33.addFile(u"../icons/record_voice_over_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon33, "")
        icon34 = QIcon()
        icon34.addFile(u"../icons/panorama_photosphere_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon34, "")
        icon35 = QIcon()
        icon35.addFile(u"../icons/pan_tool_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon35, "")
        self.comboBox_6.addItem(icon31, "")
        icon36 = QIcon()
        icon36.addFile(u"../icons/camera_video_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon36, "")
        icon37 = QIcon()
        icon37.addFile(u"../icons/network_intelligence_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon37, "")
        icon38 = QIcon()
        icon38.addFile(u"../icons/motion_blur_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon38, "")
        self.comboBox_6.addItem(icon34, "")
        self.comboBox_6.addItem(icon5, "")
        icon39 = QIcon()
        icon39.addFile(u"../icons/cadence_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon39, "")
        self.comboBox_6.addItem(icon34, "")
        self.comboBox_6.addItem(icon34, "")
        self.comboBox_6.addItem(icon14, "")
        self.comboBox_6.addItem(icon31, "")
        icon40 = QIcon()
        icon40.addFile(u"../icons/piano_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon40, "")
        self.comboBox_6.addItem(icon31, "")
        icon41 = QIcon()
        icon41.addFile(u"../icons/view_in_ar_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_6.addItem(icon41, "")
        self.comboBox_6.addItem(icon34, "")
        self.comboBox_6.addItem(icon41, "")
        self.comboBox_6.addItem(icon34, "")
        self.comboBox_6.setObjectName(u"comboBox_6")

        self.gridLayout.addWidget(self.comboBox_6, 10, 0, 1, 2)

        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")

        self.gridLayout.addWidget(self.label_7, 11, 0, 1, 2)

        self.comboBox_7 = QComboBox(Form)
        icon42 = QIcon()
        icon42.addFile(u"../icons/alarm_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_7.addItem(icon42, "")
        icon43 = QIcon()
        icon43.addFile(u"../icons/schedule_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_7.addItem(icon43, "")
        icon44 = QIcon()
        icon44.addFile(u"../icons/pace_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_7.addItem(icon44, "")
        self.comboBox_7.addItem(icon44, "")
        self.comboBox_7.addItem(icon44, "")
        self.comboBox_7.addItem(icon11, "")
        self.comboBox_7.setObjectName(u"comboBox_7")

        self.gridLayout.addWidget(self.comboBox_7, 12, 0, 1, 2)

        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout.addWidget(self.label_8, 13, 0, 1, 2)

        self.comboBox_8 = QComboBox(Form)
        icon45 = QIcon()
        icon45.addFile(u"../icons/diversity_3_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_8.addItem(icon45, "")
        icon46 = QIcon()
        icon46.addFile(u"../icons/hard_drive_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_8.addItem(icon46, "")
        self.comboBox_8.addItem(icon46, "")
        self.comboBox_8.setObjectName(u"comboBox_8")

        self.gridLayout.addWidget(self.comboBox_8, 14, 0, 1, 2)

        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")

        self.gridLayout.addWidget(self.label_9, 15, 0, 1, 2)

        self.comboBox_9 = QComboBox(Form)
        icon47 = QIcon()
        icon47.addFile(u"../icons/dropper_eye_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_9.addItem(icon47, "")
        icon48 = QIcon()
        icon48.addFile(u"../icons/closed_caption_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_9.addItem(icon48, "")
        icon49 = QIcon()
        icon49.addFile(u"../icons/settings_applications_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_9.addItem(icon49, "")
        icon50 = QIcon()
        icon50.addFile(u"../icons/contrast_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_9.addItem(icon50, "")
        self.comboBox_9.addItem(icon15, "")
        icon51 = QIcon()
        icon51.addFile(u"../icons/radio_button_unchecked_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_9.addItem(icon51, "")
        icon52 = QIcon()
        icon52.addFile(u"../icons/visibility_off_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_9.addItem(icon52, "")
        self.comboBox_9.addItem(icon17, "")
        self.comboBox_9.setObjectName(u"comboBox_9")

        self.gridLayout.addWidget(self.comboBox_9, 16, 0, 1, 2)

        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")

        self.gridLayout.addWidget(self.label_10, 17, 0, 1, 2)

        self.comboBox_10 = QComboBox(Form)
        icon53 = QIcon()
        icon53.addFile(u"../icons/html_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_10.addItem(icon53, "")
        icon54 = QIcon()
        icon54.addFile(u"../icons/download_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_10.addItem(icon54, "")
        icon55 = QIcon()
        icon55.addFile(u"../icons/http_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_10.addItem(icon55, "")
        self.comboBox_10.setObjectName(u"comboBox_10")

        self.gridLayout.addWidget(self.comboBox_10, 18, 0, 1, 2)

        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")

        self.gridLayout.addWidget(self.label_11, 19, 0, 1, 2)

        self.comboBox_11 = QComboBox(Form)
        icon56 = QIcon()
        icon56.addFile(u"../icons/key_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_11.addItem(icon56, "")
        self.comboBox_11.addItem(icon42, "")
        self.comboBox_11.addItem(icon43, "")
        icon57 = QIcon()
        icon57.addFile(u"../icons/face_4_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_11.addItem(icon57, "")
        icon58 = QIcon()
        icon58.addFile(u"../icons/featured_seasonal_and_gifts_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.comboBox_11.addItem(icon58, "")
        self.comboBox_11.setObjectName(u"comboBox_11")

        self.gridLayout.addWidget(self.comboBox_11, 20, 0, 1, 2)


        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"Filters", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"Clear", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Platform", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("Form", u"Phone browser", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("Form", u"Web browser", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("Form", u"Windows", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("Form", u"macOS", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("Form", u"Linux", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("Form", u"Android", None))
        self.comboBox_2.setItemText(6, QCoreApplication.translate("Form", u"iOS", None))

        self.label_3.setText(QCoreApplication.translate("Form", u"Price", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("Form", u"Free", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("Form", u"On Sale", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("Form", u"Paid", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("Form", u"$5 or less", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("Form", u"$15 or less", None))

        self.label_4.setText(QCoreApplication.translate("Form", u"When", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("Form", u"Last Day", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("Form", u"Last 7 days", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("Form", u"Last 30 days", None))

        self.label_5.setText(QCoreApplication.translate("Form", u"Genre", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("Form", u"Action", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("Form", u"Adventure", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("Form", u"Card Game", None))
        self.comboBox_5.setItemText(3, QCoreApplication.translate("Form", u"Educational", None))
        self.comboBox_5.setItemText(4, QCoreApplication.translate("Form", u"Fighting", None))
        self.comboBox_5.setItemText(5, QCoreApplication.translate("Form", u"Interactive Fiction", None))
        self.comboBox_5.setItemText(6, QCoreApplication.translate("Form", u"Platformer", None))
        self.comboBox_5.setItemText(7, QCoreApplication.translate("Form", u"Puzzle", None))
        self.comboBox_5.setItemText(8, QCoreApplication.translate("Form", u"Racing", None))
        self.comboBox_5.setItemText(9, QCoreApplication.translate("Form", u"Rhytm", None))
        self.comboBox_5.setItemText(10, QCoreApplication.translate("Form", u"Role Playing", None))
        self.comboBox_5.setItemText(11, QCoreApplication.translate("Form", u"Shooter", None))
        self.comboBox_5.setItemText(12, QCoreApplication.translate("Form", u"Simulation", None))
        self.comboBox_5.setItemText(13, QCoreApplication.translate("Form", u"Sports", None))
        self.comboBox_5.setItemText(14, QCoreApplication.translate("Form", u"Strategy", None))
        self.comboBox_5.setItemText(15, QCoreApplication.translate("Form", u"Survival", None))
        self.comboBox_5.setItemText(16, QCoreApplication.translate("Form", u"Visual Novel", None))
        self.comboBox_5.setItemText(17, QCoreApplication.translate("Form", u"Other", None))

        self.label_6.setText(QCoreApplication.translate("Form", u"Input Methods", None))
        self.comboBox_6.setItemText(0, QCoreApplication.translate("Form", u"Keyboard", None))
        self.comboBox_6.setItemText(1, QCoreApplication.translate("Form", u"Mouse", None))
        self.comboBox_6.setItemText(2, QCoreApplication.translate("Form", u"Xbox controller", None))
        self.comboBox_6.setItemText(3, QCoreApplication.translate("Form", u"Gamepad (any)", None))
        self.comboBox_6.setItemText(4, QCoreApplication.translate("Form", u"Joystick", None))
        self.comboBox_6.setItemText(5, QCoreApplication.translate("Form", u"Touchscreen", None))
        self.comboBox_6.setItemText(6, QCoreApplication.translate("Form", u"Voice control", None))
        self.comboBox_6.setItemText(7, QCoreApplication.translate("Form", u"Oculus Rift", None))
        self.comboBox_6.setItemText(8, QCoreApplication.translate("Form", u"Leap Motion", None))
        self.comboBox_6.setItemText(9, QCoreApplication.translate("Form", u"Wiimote", None))
        self.comboBox_6.setItemText(10, QCoreApplication.translate("Form", u"Kinect", None))
        self.comboBox_6.setItemText(11, QCoreApplication.translate("Form", u"NeuroSky Mindwave", None))
        self.comboBox_6.setItemText(12, QCoreApplication.translate("Form", u"Accelerometer", None))
        self.comboBox_6.setItemText(13, QCoreApplication.translate("Form", u"OSVR (Open-Source Virtual Reality)", None))
        self.comboBox_6.setItemText(14, QCoreApplication.translate("Form", u"Smartphone", None))
        self.comboBox_6.setItemText(15, QCoreApplication.translate("Form", u"Dance pad", None))
        self.comboBox_6.setItemText(16, QCoreApplication.translate("Form", u"HTC Vive", None))
        self.comboBox_6.setItemText(17, QCoreApplication.translate("Form", u"Google Daydream VR", None))
        self.comboBox_6.setItemText(18, QCoreApplication.translate("Form", u"Google Cardboard VR", None))
        self.comboBox_6.setItemText(19, QCoreApplication.translate("Form", u"Playstation controller", None))
        self.comboBox_6.setItemText(20, QCoreApplication.translate("Form", u"MIDI controller", None))
        self.comboBox_6.setItemText(21, QCoreApplication.translate("Form", u"Joy-Con", None))
        self.comboBox_6.setItemText(22, QCoreApplication.translate("Form", u"Magic Leap", None))
        self.comboBox_6.setItemText(23, QCoreApplication.translate("Form", u"Oculus Quest", None))
        self.comboBox_6.setItemText(24, QCoreApplication.translate("Form", u"Windows Mixed Reality", None))
        self.comboBox_6.setItemText(25, QCoreApplication.translate("Form", u"Valve Index", None))

        self.label_7.setText(QCoreApplication.translate("Form", u"Average session length", None))
        self.comboBox_7.setItemText(0, QCoreApplication.translate("Form", u"A few seconds", None))
        self.comboBox_7.setItemText(1, QCoreApplication.translate("Form", u"A few minutes", None))
        self.comboBox_7.setItemText(2, QCoreApplication.translate("Form", u"About a half-hour", None))
        self.comboBox_7.setItemText(3, QCoreApplication.translate("Form", u"About an hour", None))
        self.comboBox_7.setItemText(4, QCoreApplication.translate("Form", u"A few hours", None))
        self.comboBox_7.setItemText(5, QCoreApplication.translate("Form", u"Days or more", None))

        self.label_8.setText(QCoreApplication.translate("Form", u"Multiplayer features", None))
        self.comboBox_8.setItemText(0, QCoreApplication.translate("Form", u"Local mutiplayer", None))
        self.comboBox_8.setItemText(1, QCoreApplication.translate("Form", u"Server-based networked multiplayer", None))
        self.comboBox_8.setItemText(2, QCoreApplication.translate("Form", u"Ad-hoc networked multiplayer", None))

        self.label_9.setText(QCoreApplication.translate("Form", u"Accessibility features", None))
        self.comboBox_9.setItemText(0, QCoreApplication.translate("Form", u"Color-blind friendly", None))
        self.comboBox_9.setItemText(1, QCoreApplication.translate("Form", u"Subtitles", None))
        self.comboBox_9.setItemText(2, QCoreApplication.translate("Form", u"Configurable controls", None))
        self.comboBox_9.setItemText(3, QCoreApplication.translate("Form", u"High-contrast", None))
        self.comboBox_9.setItemText(4, QCoreApplication.translate("Form", u"Interactive tutorial", None))
        self.comboBox_9.setItemText(5, QCoreApplication.translate("Form", u"One button", None))
        self.comboBox_9.setItemText(6, QCoreApplication.translate("Form", u"Blind friendly", None))
        self.comboBox_9.setItemText(7, QCoreApplication.translate("Form", u"Textless", None))

        self.label_10.setText(QCoreApplication.translate("Form", u"Type", None))
        self.comboBox_10.setItemText(0, QCoreApplication.translate("Form", u"HTML5", None))
        self.comboBox_10.setItemText(1, QCoreApplication.translate("Form", u"Downloadable", None))
        self.comboBox_10.setItemText(2, QCoreApplication.translate("Form", u"Flash", None))

        self.label_11.setText(QCoreApplication.translate("Form", u"Misc", None))
        self.comboBox_11.setItemText(0, QCoreApplication.translate("Form", u"With Steam keys", None))
        self.comboBox_11.setItemText(1, QCoreApplication.translate("Form", u"In game jams", None))
        self.comboBox_11.setItemText(2, QCoreApplication.translate("Form", u"Not in game jams", None))
        self.comboBox_11.setItemText(3, QCoreApplication.translate("Form", u"With demos", None))
        self.comboBox_11.setItemText(4, QCoreApplication.translate("Form", u"Featured", None))

    # retranslateUi

